#include <Python.h>
#include <marshal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#ifdef MS_WINDOWS
#include <windows.h>
#else
#include <unistd.h>
#endif

#include "embed.h"

/* Generated by tools/make_payload.py: encodings & friends frozen as
 * marshalled code so a warm start never opens stdlib.zip. */
extern const struct _frozen taipan_frozen_modules[];

static PyStatus add_search_path(PyWideStringList *list, const char *path) {
    wchar_t *w = Py_DecodeLocale(path, NULL);
    if (w == NULL)
        return PyStatus_Error("taipan: cannot decode search path");
    PyStatus status = PyWideStringList_Append(list, w);
    PyMem_RawFree(w);
    return status;
}

/* Load a previously cached marshalled code object; NULL on any miss.
 * The path already encodes runtime tag + script path + content hash, so a
 * readable, well-formed file can never be stale. */
static PyObject *load_cached_code(const char *pyc_path) {
    FILE *f = fopen(pyc_path, "rb");
    if (f == NULL)
        return NULL;
    char *buf = NULL;
    long n = 0;
    if (fseek(f, 0, SEEK_END) == 0 && (n = ftell(f)) > 0 &&
        fseek(f, 0, SEEK_SET) == 0 && (buf = malloc((size_t)n)) != NULL &&
        fread(buf, 1, (size_t)n, f) != (size_t)n) {
        free(buf);
        buf = NULL;
    }
    fclose(f);
    if (buf == NULL)
        return NULL;
    PyObject *code = PyMarshal_ReadObjectFromString(buf, n);
    free(buf);
    if (code == NULL) {
        PyErr_Clear();
        return NULL;
    }
    if (!PyCode_Check(code)) {
        Py_DECREF(code);
        return NULL;
    }
    return code;
}

/* Write the marshalled code object atomically (tmp + rename). Best-effort:
 * failure only means the next run compiles again. */
static void store_cached_code(PyObject *code, const char *pyc_path) {
    PyObject *bytes = PyMarshal_WriteObjectToString(code, Py_MARSHAL_VERSION);
    if (bytes == NULL) {
        PyErr_Clear();
        return;
    }
#ifdef MS_WINDOWS
    unsigned long pid = GetCurrentProcessId();
#else
    unsigned long pid = (unsigned long)getpid();
#endif
    char tmp[4200];
    int n = snprintf(tmp, sizeof tmp, "%s.tmp.%lu", pyc_path, pid);
    if (n <= 0 || (size_t)n >= sizeof tmp) {
        Py_DECREF(bytes);
        return;
    }
    FILE *f = fopen(tmp, "wb");
    if (f != NULL) {
        size_t len = (size_t)PyBytes_GET_SIZE(bytes);
        int ok = fwrite(PyBytes_AS_STRING(bytes), 1, len, f) == len;
        ok = fclose(f) == 0 && ok;
        if (ok) {
#ifdef MS_WINDOWS
            if (!MoveFileExA(tmp, pyc_path, MOVEFILE_REPLACE_EXISTING))
                remove(tmp);
#else
            if (rename(tmp, pyc_path) != 0)
                remove(tmp);
#endif
        } else {
            remove(tmp);
        }
    }
    Py_DECREF(bytes);
}

/* Execute a code object as __main__ with __file__ set. Error handling
 * mirrors PyRun_SimpleFile: PyErr_Print finalizes and exits the process on
 * SystemExit, prints a traceback otherwise. */
static int exec_module_code(PyObject *code, const char *script_path) {
    PyObject *mod = PyImport_AddModule("__main__"); /* borrowed */
    if (mod == NULL) {
        PyErr_Print();
        return 1;
    }
    PyObject *dict = PyModule_GetDict(mod); /* borrowed */
    PyObject *file = PyUnicode_DecodeFSDefault(script_path);
    if (file == NULL || PyDict_SetItemString(dict, "__file__", file) < 0) {
        Py_XDECREF(file);
        PyErr_Print();
        return 1;
    }
    Py_DECREF(file);
    PyObject *result = PyEval_EvalCode(code, dict, dict);
    if (result == NULL) {
        PyErr_Print();
        return 1;
    }
    Py_DECREF(result);
    return 0;
}

int taipan_run_file(const char *stdlib_path, const char *extra_sys_path,
                 int precompile_extra, const char *script_path,
                 const char *script_source, const char *pyc_path,
                 int argc, char **argv) {
    PyStatus status;
    PyConfig config;

    PyImport_FrozenModules = taipan_frozen_modules;

    /* Isolated: ignore PYTHON* env vars, no user site dir. On top of that,
     * skip the `site` module entirely and never write .pyc files — both are
     * startup cost we don't want, and sys.path is fully explicit below. */
    PyConfig_InitIsolatedConfig(&config);
    config.site_import = 0;
    config.write_bytecode = 0;
    config.parse_argv = 0;
    config.use_frozen_modules = 1;

    status = PyConfig_SetBytesString(&config, &config.program_name, "taipan");
    if (PyStatus_Exception(status)) goto fail;

    /* No config.home, no path probing: sys.path is exactly what we say. */
    config.module_search_paths_set = 1;
    status = add_search_path(&config.module_search_paths, stdlib_path);
    if (PyStatus_Exception(status)) goto fail;

#ifdef MS_WINDOWS
    /* On Windows the stdlib C extensions are separate .pyd files, extracted
     * to a DLLs/ dir next to stdlib.zip. Their support DLLs (OpenSSL,
     * sqlite3, libffi) sit beside them and resolve via the loader's
     * DLL-load-dir search. Paths from the Zig side always use '/'. */
    {
        const char *slash = strrchr(stdlib_path, '/');
        if (slash != NULL) {
            char dlls_dir[4096];
            int n = snprintf(dlls_dir, sizeof dlls_dir, "%.*s/DLLs",
                             (int)(slash - stdlib_path), stdlib_path);
            if (n > 0 && (size_t)n < sizeof dlls_dir) {
                status = add_search_path(&config.module_search_paths, dlls_dir);
                if (PyStatus_Exception(status)) goto fail;
            }
        }
    }
#endif

    if (extra_sys_path && extra_sys_path[0]) {
        status = add_search_path(&config.module_search_paths, extra_sys_path);
        if (PyStatus_Exception(status)) goto fail;
    }

    status = PyConfig_SetBytesArgv(&config, argc, argv);
    if (PyStatus_Exception(status)) goto fail;

    status = Py_InitializeFromConfig(&config);
    if (PyStatus_Exception(status)) goto fail;
    PyConfig_Clear(&config);

    /* One-time bytecode precompile of a fresh dependency env, in-process so
     * no external python is ever needed. Failure only costs speed. */
    if (precompile_extra && extra_sys_path && extra_sys_path[0]) {
        char buf[4200];
        int n = snprintf(buf, sizeof buf,
                         "import compileall\n"
                         "compileall.compile_dir('%s', quiet=2)\n",
                         extra_sys_path);
        if (n > 0 && (size_t)n < sizeof buf && PyRun_SimpleString(buf) != 0)
            PyErr_Clear();
    }

    /* The script itself: cached marshalled code when available, else compile
     * once and cache, so warm startup no longer depends on script size. */
    PyObject *code = NULL;
    if (pyc_path && pyc_path[0])
        code = load_cached_code(pyc_path);
    if (code == NULL) {
        code = Py_CompileString(script_source, script_path, Py_file_input);
        if (code == NULL) {
            PyErr_Print(); /* SyntaxError */
            Py_FinalizeEx();
            return 1;
        }
        if (pyc_path && pyc_path[0])
            store_cached_code(code, pyc_path);
    }

    int rc = exec_module_code(code, script_path);
    Py_DECREF(code);

    if (Py_FinalizeEx() < 0 && rc == 0)
        rc = 120;
    return rc != 0 ? 1 : 0;

fail:
    PyConfig_Clear(&config);
    if (PyStatus_IsExit(status))
        return status.exitcode;
    Py_ExitStatusException(status); /* prints and aborts */
    return 1;
}
